services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        env_file: ./.env

        volumes:
            - ./www:/var/www/html

        command: sleep infinity
        restart: unless-stopped

        network_mode: host

        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE:      ${MYSQL_DATABASE}
            MYSQL_USER:          ${MYSQL_USER}
            MYSQL_PASSWORD:      ${MYSQL_PASSWORD}


