services:

  lamp-www:

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - "../www:/var/www/html"

    restart: unless-stopped

    ports:
      - 8080:80

  db:
    image: mysql

    restart: unless-stopped

    env_file: ./.env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}

    ports:
      - 3306:3306
