services:

  # Apache and PHP setup
  lamp-www:
    container_name: lamp-www
    restart: unless-stopped
    # via Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # Running on port 8080
    ports:
      - 8080:8080
    # Need MySQL up too
    depends_on:
      - lamp-db
    # Data stores
    volumes:
      # Map WWW host folder into container
      - "../www:/var/www/html"

  lamp-db:
    container_name: lamp-db
    restart: unless-stopped
    # Official MySQL image
    image: mysql:latest
    # Set root password, and create a test DB
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "helloWorld"
    # Data stores
    volumes:
      # Contents for test DB mapped into container
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Provide a persistent DB store
      - mysql-data:/var/lib/mysql

volumes:
  # Persist MySQL databases through rebuilds
  mysql-data:

