services:

  lamp-www:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: lamp-www

    volumes:
      - "../www:/var/www/html"

    restart: unless-stopped

    depends_on:
      - lamp-db

    networks:
      - net

    ports:
      - 8080:80

  lamp-db:

    image: mysql:latest

    container_name: lamp-db

    restart: unless-stopped

    env_file: ./.env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}

    ports:
      - 3306:3306

    networks:
      - net

networks:
  net:
    driver: bridge
