services:
  lamp-www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lamp-www
    depends_on:
      - lamp-db
    volumes:
      - "../www:/var/www/html"
    restart: unless-stopped
    ports:
      - 8080:80

  lamp-db:
    image: mysql:latest
    container_name: lamp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:

