services:

  lamp-www:

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # - ../..:/workspaces:cached
      - "../www:/var/www/html"

    command: sleep infinity
    restart: unless-stopped

    network_mode: host

    ports:
      - 8080

    # db:
    #     image: mysql

    #     restart: unless-stopped

    #     env_file: ./.env

    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_DATABASE:      ${MYSQL_DATABASE}
    #         MYSQL_USER:          ${MYSQL_USER}
    #         MYSQL_PASSWORD:      ${MYSQL_PASSWORD}


